name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Build application
        run: npm run build

      - name: Create deployment package
        run: |
          tar -czf deployment.tar.gz dist/ node_modules/ package.json prisma/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment.tar.gz

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Navigate to application directory
            cd ${{ secrets.APP_PATH || '/var/www/todo' }}/server

            # Stop PM2 process
            pm2 stop todo-server || true

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          source: 'deployment.tar.gz'
          target: ${{ secrets.APP_PATH || '/var/www/todo' }}/server

      - name: Extract and restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Navigate to application directory
            cd ${{ secrets.APP_PATH || '/var/www/todo' }}

            # Extract deployment package
            tar -xzf deployment.tar.gz -C server/

            # Navigate to server directory
            cd server

            # Run database migrations if needed
            npx prisma migrate deploy || true

            # Start application with PM2
            pm2 start dist/main.js --name "todo-server" -i max || pm2 restart todo-server

            # Save PM2 configuration
            pm2 save

            # Clean up
            cd ..
            rm -f deployment.tar.gz

            echo "Deployment completed successfully!"
